### ISSUE TITLE
Xarm measurement

### ISSUE THREAD

**Issue by YoshinoriFujii** [gw-vis/ETMX#3]
### displacement transfer functions
      -- GND -> IP, IP -> Xarm-out (~TM)
        or
      -- GND -> BF, BF -> Xarm-out (~TM)

priority | Input channel | Output channel
-- | -- | --
  | [X] ITMX-GND-L | IP-L ( [X] LVDT / [X] ACC / [X] blended)
  - [ ] do mdoeling

### force transfer functions

priority | Input channel stage | Input channel DoF | Note
-- | -- | -- | --
~O~ | TM | ~L~ | done
O |   | P |  
  |   | Y |  
  |   |   |  
O | IM | L |  
~O~ |   | ~V~ | done but the result was not much clear  
  |   | P |  
  |   | Y |  
  |   |   |  
~O~ | MN | ~L~ |  ~measuring~ done
  |   | P |  
  |   | Y |  
  |   |   |  
O | IP | L | with seismic noise in spectrum
  |   |   |    
... | F1 | V |  
~O~ |  BF-GAS | ~V~ |  done
 O | BF | L 

## reference
[1] https://gwdoc.icrr.u-tokyo.ac.jp/DocDB/0082/G1808219/005/presentation_gwadw_20180517_miyamoto_v5.pdf

**Comment by YoshinoriFujii** [comment]
![513031dc-bee6-41a1-b9e4-534ea8254afa](https://user-images.githubusercontent.com/37787512/50473252-8f7aa200-09ff-11e9-9fb9-a042436a273f.jpg)

**Comment by YoshinoriFujii** [comment]
### DO REMEMBER
- request DOWN to ALS_PDHX guardian, before starting the measurements.
- In DOWN state, ALS_PDHX guardian does not try to feedback the signals from PR2/PR3 to IMC or like that. It would be safer to do this, for some optics like PSL, IMC.

**Comment by YoshinoriFujii** [comment]
Alignment note:
- Since ETMX_TM_Yaw was drifted by ~1 urad at Tilt-OpLev, I tried to change the Yaw position:
from -97.5 to -98. 5 in K1:VIS-ETMX_TM_OPLEV_TILT_PIT_OUTMON, by changing:
from 1338 to 1341 in K1:VIS-ETMX_BF_DAMP_Y_OFFSET,
on 20:58 JST, Dec. 27th, 2018.


see /users/VISsvn/TypeApayload/ETMX/TF/Measurement/20181227

**Comment by YoshinoriFujii** [comment]
### reference

![image](https://user-images.githubusercontent.com/37787512/50482600-c5814b80-0a2a-11e9-827e-276cfc2627e0.png)

**Comment by YoshinoriFujii** [comment]
Transfer function from MCL_OUT to delta freq is:
zpk([],[0.101499+i*0.942551;0.101499-i*0.942551],-7.757,"n")gain(1.2)gain(0.0006104)
gain(120,"dB")gain(2)

[1] pole at zpk(|z|=0.948, Q=4.67)

**Comment by YoshinoriFujii** [comment]
### result
- [ ] unit is correct???

### references
see /users/VIS/TypeA/general/Xarm_measurement/*

![etmx_tm_test_l_exctodisplacement](https://user-images.githubusercontent.com/37787512/50489037-d0e36f80-0a48-11e9-99d2-b48e1c2ab662.png)

**Comment by YoshinoriFujii** [comment]
Alignment note:
from -98.75 to -98. 5 in K1:VIS-ETMX_TM_OPLEV_TILT_PIT_OUTMON, by changing:
from 1341 to 1340 in K1:VIS-ETMX_BF_DAMP_Y_OFFSET,
on 24:44 JST, Dec. 27th, 2018.

**Comment by YoshinoriFujii** [comment]
Alignment note:
from 497 to 498 in K1:VIS-ITMX_BF_DAMP_Y_OFFSET,
on 6:51 JST, Dec. 28th, 2018.

**Comment by YoshinoriFujii** [comment]
Alignment note:
from 499 to 501 in K1:VIS-ITMX_BF_DAMP_Y_OFFSET,
on 8am? JST, Dec. 28th, 2018.

**Comment by YoshinoriFujii** [comment]
> unit is correct???

currently, the unit of the vertical axis is [m/count]. In order to convert [count] to [N], actuator efficiency is necessary.
- [ ] get the values.

**Comment by YoshinoriFujii** [comment]
> ### displacement transfer functions
see `/users/VISsvn/TypeAtower/ETMX/TF/Measurements/20181228/`

**Comment by YoshinoriFujii** [comment]
### reference
actuation efficiency:
https://gwdoc.icrr.u-tokyo.ac.jp/cgi-bin/private/DocDB/ShowDocument?docid=6948

**Comment by YoshinoriFujii** [comment]
### Still in a development process (part2):
transfer functions form MNL actuator to Xarm-out in [m/count]

![etmx_mn_test_l_exctodisplacement](https://user-images.githubusercontent.com/37787512/50503874-35d0b100-0aad-11e9-8a92-734b7d677f85.png)

**Comment by YoshinoriFujii** [comment]
## test for VI performance measurement
- [X] check if it is possible to lock Xarm w/o controls (except for BF-Y)
  - [ ] w/ ITMX

**Comment by YoshinoriFujii** [comment]
### BFGASexc measurement

![image](https://user-images.githubusercontent.com/37787512/50566124-5765bd00-0d79-11e9-93bf-0709f6ec60a0.png)

**Comment by YoshinoriFujii** [comment]
### 2019.1.1,
- Note of a transfer function from BF-GAS.
  - when the BF-GAS was excited at the main resonance:

![image](https://user-images.githubusercontent.com/37787512/50570403-3d55ca00-0dcd-11e9-8876-a7178a682fc9.png)

**Comment by YoshinoriFujii** [comment]
Frequency[Hz] | exc_amp in counts | coherence  
-- | -- | --
781 | 10 |  
813 | 10 |  
844 | 20 |  
906 | 20 |  
938 | 30 |  
1.063 | 30 |  
1.125 | 100 |  
1.25 | 100 |  
1.313 | 200 |  
1.375 | 200 |  
1.437 | 500 |  
1.5 | 1000 |  
1.563 |   |  
1.625 |   |  
1.688 |   |  
  |   |  
1.75 |   |  
1.8125 |   |  
1.875 |   |  
1.9375 |   |  
2 |   |  
2.0625 |   |  
2.125 |   |  
2.1875 |   |  
2.25 |   |  
2.3125 |   |  
2.375 |   |

**Comment by YoshinoriFujii** [comment]
ls ITMX/TF/Measurements/20181227/done/*          
ITMX/TF/Measurements/20181227/done/ITMX_TML_exc_10000c_1Hz_20181227.xml

ITMX/TF/Measurements/20181227/done/MNL:
ITMX_MNL_exc_10000c_1-1.2Hz_20181228.xml
ITMX_MNL_exc_10000c_1.5-1.8Hz_20181228.xml
ITMX_MNL_exc_10000c_10-100Hz_20181228.xml
ITMX_MNL_exc_10000c_10-20Hz_20181228.xml
ITMX_MNL_exc_10000c_2.8-3Hz_20181228.xml
ITMX_MNL_exc_10000c_3.8-5Hz_20181228.xml
ITMX_MNL_exc_10000c_3.8-7Hz_20181228.xml
ITMX_MNL_exc_10000c_8-10Hz_20181228.xml

ITMX/TF/Measurements/20181227/done/TML:
ITMX_MNL_exc_10000c_3.8-4.5Hz_20181228.xml
ITMX_TML_exc_10000c_1-2Hz_20181227.xml
ITMX_TML_exc_10000c_1-5Hz_20181227.xml
ITMX_TML_exc_10000c_1-7Hz_20181227.xml
ITMX_TML_exc_10000c_10-100Hz_20181227.xml
ITMX_TML_exc_10000c_8-10Hz_20181227.xml
filename_list.log

**Comment by YoshinoriFujii** [comment]
plots, being plotted:
https://drive.google.com/open?id=1L70tU8eIVYCy5C9x-5gIeVtdihJFoMS4bo3TUW5yVAc

**Comment by YoshinoriFujii** [comment]
### Todo
- [ ] make and export simulated transfer functions.

**Comment by YoshinoriFujii** [comment]
### directories under /users/VISsvn/TypeAtower/
`$ ls /users/VISsvn/TypeAtower/ETMX/TF/Measurements/20190104/`
**IPL/**

ETMX_IPL_exc_0.781-0.813Hz_20190104.xml
ETMX_IPL_exc_0.813Hz_20190104.xml
ETMX_IPL_exc_0.844-0.906Hz_20190104.xml
ETMX_IPL_exc_0.938-1.063Hz_20190104.xml
ETMX_IPL_exc_1.125-1.25Hz_20190104.xml
ETMX_IPL_exc_1.313-1.375Hz_20190104.xml
ETMX_IPL_exc_1.375-1.437Hz_20190104.xml
ETMX_IPL_exc_1.437-1.5Hz_20190104.xml
ETMX_IPL_exc_1.563-1.58Hz_20190104.xml
ETMX_IPL_exc_1.58-1.625Hz_20190104.xml
ETMX_IPL_exc_1.625-1.688Hz_20190104.xml
ETMX_IPL_exc_1.688Hz_20190104.xml
ETMX_IPL_exc_1.75Hz_20190104.xml
ETMX_IPL_exc_1.8125Hz_20190104.xml
ETMX_IPL_exc_1.89Hz_20190104.xml
ETMX_IPL_exc_1.95Hz_20190104.xml
ETMX_IPL_exc_2Hz_20190104.xml

**Comment by YoshinoriFujii** [comment]
brief summary:
[summary_2019Feb](https://www.evernote.com/l/AoN5QoJCeSVNjaMLpjNe20TXi0araLcQftk/ "summary_2019Feb")
